name: attendence_manager
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  table_calendar: ^3.0.9
  intl: ^0.18.1
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2 
  share_plus: ^7.2.1          

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
